"""initial_schema

Revision ID: edf81cf71744
Revises: 
Create Date: 2026-05-20 09:53:33.978949

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'edf81cf71744'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('discoverable', sa.Boolean(), nullable=True),
    sa.Column('indexable', sa.Boolean(), nullable=False),
    sa.Column('memorial', sa.Boolean(), nullable=False),
    sa.Column('hide_collections', sa.Boolean(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=True),
    sa.Column('uri', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('private_key', sa.Text(), nullable=False),
    sa.Column('inbox_url', sa.String(), nullable=False),
    sa.Column('shared_inbox_url', sa.String(), nullable=False),
    sa.Column('avatar_file_name', sa.String(), nullable=True),
    sa.Column('avatar_remote_url', sa.String(), nullable=True),
    sa.Column('avatar_content_type', sa.String(), nullable=True),
    sa.Column('header_file_name', sa.String(), nullable=True),
    sa.Column('header_remote_url', sa.String(), nullable=False),
    sa.Column('header_content_type', sa.String(), nullable=True),
    sa.Column('moved_to_account_id', sa.BigInteger(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(), nullable=True),
    sa.Column('silenced_at', sa.DateTime(), nullable=True),
    sa.Column('suspension_origin', sa.Integer(), nullable=True),
    sa.Column('sensitized_at', sa.DateTime(), nullable=True),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('announcements',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('notification_sent_at', sa.DateTime(), nullable=True),
    sa.Column('all_day', sa.Boolean(), nullable=False),
    sa.Column('status_ids', sa.ARRAY(sa.BigInteger()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('conversations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('parent_status_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_account_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_emojis',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('shortcode', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('image_file_name', sa.String(), nullable=True),
    sa.Column('image_content_type', sa.String(), nullable=True),
    sa.Column('image_file_size', sa.Integer(), nullable=True),
    sa.Column('image_remote_url', sa.String(), nullable=True),
    sa.Column('image_updated_at', sa.DateTime(), nullable=True),
    sa.Column('visible_in_picker', sa.Boolean(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shortcode', 'domain', name='index_custom_emojis_on_shortcode_and_domain')
    )
    op.create_table('oauth_access_tokens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.Column('application_id', sa.BigInteger(), nullable=True),
    sa.Column('resource_owner_id', sa.BigInteger(), nullable=True),
    sa.Column('expires_in', sa.Integer(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_ip', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('oauth_applications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('uid', sa.String(), nullable=False),
    sa.Column('secret', sa.String(), nullable=False),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('scopes', sa.String(), nullable=False),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('confidential', sa.Boolean(), nullable=False),
    sa.Column('superapp', sa.Boolean(), nullable=False),
    sa.Column('owner_id', sa.BigInteger(), nullable=True),
    sa.Column('owner_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('usable', sa.Boolean(), nullable=True),
    sa.Column('listable', sa.Boolean(), nullable=True),
    sa.Column('trendable', sa.Boolean(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('requested_review_at', sa.DateTime(), nullable=True),
    sa.Column('last_status_at', sa.DateTime(), nullable=True),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('max_score_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_conversations',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('conversation_id', sa.BigInteger(), nullable=False),
    sa.Column('last_status_id', sa.BigInteger(), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('participant_account_ids', sa.ARRAY(sa.BigInteger()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('status_ids', sa.ARRAY(sa.BigInteger()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('unread', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'conversation_id', 'participant_account_ids', name='index_unique_conversations')
    )
    op.create_table('account_domain_blocks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'domain', name='index_account_domain_blocks_on_account_id_and_domain')
    )
    op.create_table('account_notes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('target_account_id', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['target_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'target_account_id', name='index_account_notes_on_account_id_and_target_account_id')
    )
    op.create_table('account_pins',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('target_account_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['target_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'target_account_id', name='index_account_pins_on_account_id_and_target_account_id')
    )
    op.create_table('account_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('statuses_count', sa.BigInteger(), nullable=False),
    sa.Column('following_count', sa.BigInteger(), nullable=False),
    sa.Column('followers_count', sa.BigInteger(), nullable=False),
    sa.Column('last_status_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id')
    )
    op.create_table('announcement_mutes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('announcement_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['announcement_id'], ['announcements.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'announcement_id', name='index_announcement_mutes_on_account_id_and_announcement_id')
    )
    op.create_table('blocks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('target_account_id', sa.BigInteger(), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['target_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'target_account_id', name='index_blocks_on_account_id_and_target_account_id')
    )
    op.create_table('custom_filters',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.Integer(), nullable=False),
    sa.Column('context', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('phrase', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('featured_tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('statuses_count', sa.BigInteger(), nullable=False),
    sa.Column('last_status_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'tag_id', name='index_featured_tags_on_account_id_and_tag_id')
    )
    op.create_table('follow_requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('target_account_id', sa.BigInteger(), nullable=False),
    sa.Column('show_reblogs', sa.Boolean(), nullable=False),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.Column('languages', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['target_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'target_account_id', name='index_follow_requests_on_account_id_and_target_account_id')
    )
    op.create_table('follows',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('target_account_id', sa.BigInteger(), nullable=False),
    sa.Column('show_reblogs', sa.Boolean(), nullable=False),
    sa.Column('notify', sa.Boolean(), nullable=False),
    sa.Column('languages', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['target_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'target_account_id', name='index_follows_on_account_id_and_target_account_id')
    )
    op.create_table('lists',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('replies_policy', sa.Integer(), nullable=False),
    sa.Column('exclusive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mutes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('target_account_id', sa.BigInteger(), nullable=False),
    sa.Column('hide_notifications', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['target_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'target_account_id', name='index_mutes_on_account_id_and_target_account_id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('from_account_id', sa.BigInteger(), nullable=False),
    sa.Column('activity_id', sa.BigInteger(), nullable=False),
    sa.Column('activity_type', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('filtered', sa.Boolean(), nullable=False),
    sa.Column('group_key', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['from_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('target_account_id', sa.BigInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('status_ids', sa.ARRAY(sa.BigInteger()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('rule_ids', sa.ARRAY(sa.BigInteger()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('forwarded', sa.Boolean(), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('application_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_account_id', sa.BigInteger(), nullable=True),
    sa.Column('action_taken_at', sa.DateTime(), nullable=True),
    sa.Column('action_taken_by_account_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['target_account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('statuses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('spoiler_text', sa.Text(), nullable=False),
    sa.Column('sensitive', sa.Boolean(), nullable=False),
    sa.Column('visibility', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=True),
    sa.Column('local', sa.Boolean(), nullable=True),
    sa.Column('reply', sa.Boolean(), nullable=False),
    sa.Column('in_reply_to_id', sa.BigInteger(), nullable=True),
    sa.Column('in_reply_to_account_id', sa.BigInteger(), nullable=True),
    sa.Column('reblog_of_id', sa.BigInteger(), nullable=True),
    sa.Column('application_id', sa.BigInteger(), nullable=True),
    sa.Column('conversation_id', sa.BigInteger(), nullable=True),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['reblog_of_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tag_follows',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'tag_id', name='index_tag_follows_on_account_id_and_tag_id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('encrypted_password', sa.String(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('approved', sa.Boolean(), nullable=False),
    sa.Column('disabled', sa.Boolean(), nullable=False),
    sa.Column('otp_required_for_login', sa.Boolean(), nullable=False),
    sa.Column('otp_secret', sa.String(), nullable=True),
    sa.Column('consumed_timestep', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.BigInteger(), nullable=True),
    sa.Column('locale', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmarks',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'status_id', name='index_bookmarks_on_account_id_and_status_id')
    )
    op.create_table('custom_filter_keywords',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('custom_filter_id', sa.BigInteger(), nullable=False),
    sa.Column('keyword', sa.Text(), nullable=False),
    sa.Column('whole_word', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['custom_filter_id'], ['custom_filters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_filter_statuses',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('custom_filter_id', sa.BigInteger(), nullable=False),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['custom_filter_id'], ['custom_filters.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_id', 'custom_filter_id', name='index_custom_filter_statuses_on_status_id_and_custom_filter_id')
    )
    op.create_table('favourites',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'status_id', name='index_favourites_on_account_id_and_status_id')
    )
    op.create_table('list_accounts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('list_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('follow_id', sa.BigInteger(), nullable=True),
    sa.Column('follow_request_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['lists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'list_id', name='index_list_accounts_on_account_id_and_list_id')
    )
    op.create_table('markers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('timeline', sa.String(), nullable=False),
    sa.Column('last_read_id', sa.BigInteger(), nullable=False),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'timeline', name='index_markers_on_user_id_and_timeline')
    )
    op.create_table('media_attachments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('status_id', sa.BigInteger(), nullable=True),
    sa.Column('scheduled_status_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('processing', sa.Integer(), nullable=True),
    sa.Column('file_file_name', sa.String(), nullable=True),
    sa.Column('file_content_type', sa.String(), nullable=True),
    sa.Column('file_file_size', sa.Integer(), nullable=True),
    sa.Column('file_meta', sa.JSON(), nullable=True),
    sa.Column('file_updated_at', sa.DateTime(), nullable=True),
    sa.Column('thumbnail_file_name', sa.String(), nullable=True),
    sa.Column('thumbnail_content_type', sa.String(), nullable=True),
    sa.Column('thumbnail_file_size', sa.Integer(), nullable=True),
    sa.Column('remote_url', sa.String(), nullable=False),
    sa.Column('thumbnail_remote_url', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('blurhash', sa.String(), nullable=True),
    sa.Column('shortcode', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mentions',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('silent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'status_id', name='index_mentions_on_account_id_and_status_id')
    )
    op.create_table('polls',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('options', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('cached_tallies', sa.ARRAY(sa.BigInteger()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('multiple', sa.Boolean(), nullable=False),
    sa.Column('hide_totals', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('votes_count', sa.BigInteger(), nullable=False),
    sa.Column('voters_count', sa.BigInteger(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(), nullable=True),
    sa.Column('lock_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_edits',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('spoiler_text', sa.Text(), nullable=False),
    sa.Column('sensitive', sa.Boolean(), nullable=True),
    sa.Column('ordered_media_attachment_ids', sa.ARRAY(sa.BigInteger()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('media_descriptions', sa.ARRAY(sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('poll_options', sa.ARRAY(sa.String()).with_variant(sa.JSON(), 'sqlite'), nullable=True),
    sa.Column('quote_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_pins',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'status_id', name='index_status_pins_on_account_id_and_status_id')
    )
    op.create_table('status_stats',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.Column('replies_count', sa.BigInteger(), nullable=False),
    sa.Column('reblogs_count', sa.BigInteger(), nullable=False),
    sa.Column('favourites_count', sa.BigInteger(), nullable=False),
    sa.Column('quotes_count', sa.BigInteger(), nullable=False),
    sa.Column('untrusted_reblogs_count', sa.BigInteger(), nullable=True),
    sa.Column('untrusted_favourites_count', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('status_id')
    )
    op.create_table('statuses_tags',
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('status_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['status_id'], ['statuses.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('tag_id', 'status_id')
    )
    op.create_table('poll_votes',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('poll_id', sa.BigInteger(), nullable=False),
    sa.Column('choice', sa.Integer(), nullable=False),
    sa.Column('uri', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['poll_id'], ['polls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('poll_votes')
    op.drop_table('statuses_tags')
    op.drop_table('status_stats')
    op.drop_table('status_pins')
    op.drop_table('status_edits')
    op.drop_table('polls')
    op.drop_table('mentions')
    op.drop_table('media_attachments')
    op.drop_table('markers')
    op.drop_table('list_accounts')
    op.drop_table('favourites')
    op.drop_table('custom_filter_statuses')
    op.drop_table('custom_filter_keywords')
    op.drop_table('bookmarks')
    op.drop_table('users')
    op.drop_table('tag_follows')
    op.drop_table('statuses')
    op.drop_table('reports')
    op.drop_table('notifications')
    op.drop_table('mutes')
    op.drop_table('lists')
    op.drop_table('follows')
    op.drop_table('follow_requests')
    op.drop_table('featured_tags')
    op.drop_table('custom_filters')
    op.drop_table('blocks')
    op.drop_table('announcement_mutes')
    op.drop_table('account_stats')
    op.drop_table('account_pins')
    op.drop_table('account_notes')
    op.drop_table('account_domain_blocks')
    op.drop_table('account_conversations')
    op.drop_table('tags')
    op.drop_table('oauth_applications')
    op.drop_table('oauth_access_tokens')
    op.drop_table('custom_emojis')
    op.drop_table('conversations')
    op.drop_table('announcements')
    op.drop_table('accounts')
    # ### end Alembic commands ###
